- name: Provision kafka environment
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    project_name: "kafka_firehose"

  vars_files:
    - vars/aws/kafka.yaml
    - vars/aws/aws.yaml

  tasks:
    - include: tasks/aws/keypair.yaml
    - include: tasks/aws/securitygroup.yaml
    - include: tasks/aws/instances.yaml