- name: Terminate kafka environment
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    project_name: "kafka_firehose"

  vars_files:
    - vars/aws/kafka.yaml
    - vars/aws/aws.yaml

  tasks:
    - include: tasks/aws/instances_terminate.yaml
    - include: tasks/aws/securitygroup_terminate.yaml
    - include: tasks/aws/keypair_terminate.yaml
